name = "kafein"
version = "1.0.0"

target = "erlang"

description = "TLS client for Gleam on Erlang"
licences = ["Unlicense"]
repository = { type = "github", user = "0komo", repo = "kafein" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
mug = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glisten = ">= 8.0.1 and < 9.0.0"
xtask.path = "./xtask"

[erlang]
extra_applications = ["ssl"]
