name = "kafe"
version = "1.0.0"

target = "erlang"

description = "D"
licences = ["Unlicense"]
repository = { type = "github", user = "0komo", repo = "kafe" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
toss = ">= 1.0.0 and < 2.0.0"
mug = ">= 3.1.0 and < 4.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
certifi = ">= 2.15.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[erlang]
extra_applications = ["ssl"]
